### ISSUE TITLE
Website Error, Unclosed block and 404 Not found

### ISSUE THREAD

**Issue by Tcip** [adobe-fonts/source-sans#276]
I found some errors on the demo website (https://adobe-fonts.github.io/source-sans/).

### 1. Unclosed block on line 126, Index page
```css
@media (prefers-color-scheme: dark) {
```
<details><summary>line 126</summary>

```css
@media (prefers-color-scheme: dark) {
  body {
    background-color: #222;
    color: #fff;
  }
  div:hover {
    background-color: #333;
  }
  .ribbon:before {
    background-color: rgb(221, 221, 221);
  }
  .ribbon:after {
    color: #000;
  }
```
</details>

### 2. File not found in source-sans-3.css
```
https://adobe-fonts.github.io/source-sans/WOFF2/SourceSans3VF-Upright.otf.woff2 
https://adobe-fonts.github.io/source-sans/WOFF2/SourceSans3VF-Upright.ttf.woff2 
```
